swagger: '2.0'
info:
  description: Um exemplo de aplicação Spring Boot com Thyemeleaf
  version: 1.0.0
  title: Naruto
  contact:
    name: Rafael Horochovec
    url: https://github.com/rlhorochovec
    email: rl.horochovec@gmail.com
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: /
tags:
  - name: ninja-rest-controller
    description: Ninja Rest Controller
paths:
  /api/ninjas:
    get:
      tags:
        - ninja-rest-controller
      summary: getAllNinjasPage
      operationId: getAllNinjasPageUsingGET
      produces:
        - '*/*'
      parameters:
        - name: name
          in: query
          description: name
          required: false
          type: string
        - name: page
          in: query
          description: page
          required: false
          type: integer
          default: 0
          format: int32
        - name: size
          in: query
          description: size
          required: false
          type: integer
          default: 3
          format: int32
        - name: sort
          in: query
          description: sort
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
          default: id,desc
      responses:
        '200':
          description: OK
          schema:
            type: object
            additionalProperties:
              type: object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
