swagger: '2.0'
info:
  description: Um exemplo de aplicação Spring Boot com Thyemeleaf
  version: 1.0.0
  title: Naruto
  contact:
    name: Rafael Horochovec
    url: https://github.com/rlhorochovec
    email: rl.horochovec@gmail.com
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: /
tags:
  - name: ninja-rest-controller
    description: Ninja Rest Controller
paths:
  /api/ninjas:
    get:
      tags:
        - ninja-rest-controller
      summary: getNinjas
      operationId: getNinjasUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Ninja'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /api/ninjas/{id}:
    get:
      tags:
        - ninja-rest-controller
      summary: getNinja
      operationId: getNinjaUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Ninja'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ClasseNinja:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nome:
        type: string
    title: ClasseNinja
  Ninja:
    type: object
    properties:
      classe:
        $ref: '#/definitions/ClasseNinja'
      id:
        type: integer
        format: int64
      nome:
        type: string
      vila:
        $ref: '#/definitions/Vila'
    title: Ninja
  Vila:
    type: object
    properties:
      id:
        type: integer
        format: int64
      nome:
        type: string
    title: Vila
